/**
 * Autogenerated header file for the wordclock
 *   22 words encoded
 *   30/87 empty squares
 *
 *  K W A R T I E N . .
 *  . V I J F . V O O R
 *  . O V E R . H A L F
 *  V . . W Y K E N . .
 *  . I A C H T I E N .
 *  . Z E V E N W G N .
 *  . E D R I E . E L F
 *  . S . H A J O N E .
 *  . T W A A L F . . .
 *  . . . . . . . U U R
 */

#include <stdint.h>
#include <avr/pgmspace.h>

struct Date {
  uint8_t day;
  uint8_t month;
};

static const uint32_t VIJF = (1ul << 0);
static const uint32_t TIEN = (1ul << 1);
static const uint32_t KWART = (1ul << 2);
static const uint32_t VOOR = (1ul << 3);
static const uint32_t OVER = (1ul << 4);
static const uint32_t HALF = (1ul << 5);
static const uint32_t TWAALF = (1ul << 6);
static const uint32_t EEN = (1ul << 7);
static const uint32_t TWEE = (1ul << 8);
static const uint32_t DRIE = (1ul << 9);
static const uint32_t VIER = (1ul << 10);
static const uint32_t VIJF_ = (1ul << 11);
static const uint32_t ZES = (1ul << 12);
static const uint32_t ZEVEN = (1ul << 13);
static const uint32_t ACHT = (1ul << 14);
static const uint32_t NEGEN = (1ul << 15);
static const uint32_t TIEN_ = (1ul << 16);
static const uint32_t ELF = (1ul << 17);
static const uint32_t UUR = (1ul << 18);
static const uint32_t WYKE = (1ul << 19);
static const uint32_t EN = (1ul << 20);
static const uint32_t HAJO = (1ul << 21);
static const uint32_t TROUWDAG = WYKE | EN | HAJO;

static const PROGMEM uint32_t matrix[] = {
  0,       0,      0,      0,      0,      0,       0,       262144,  262144,
  262144,  0,      0,      0,      2112,   64,      64,      64,      64,
  64,      0,      0,      4096,   0,      2097152, 2097152, 2099200, 2097152,
  32768,   256,    0,      131072, 131072, 164096,  0,       512,     2560,
  1536,    512,    4096,   0,      0,      12288,   9216,    10240,   1056768,
  1056768, 256,    32768,  128,    0,      0,       65536,   98432,   65536,
  82176,   16384,  16384,  16384,  1024,   0,       1024,    0,       0,
  524288,  524288, 524288, 524416, 32768,  0,       0,       32,      32,
  32,      32,     0,      16,     16,     16,      16,      0,       0,
  1,       1,      1,      1,      0,      8,       8,       8,       8,
  0,       0,      2,      2,      2,      6,       4,       4,       4,
  4
};

static const Date birthdays[] = { Date{ 1, 1 }, Date{ 7, 12 }, Date{ 2, 10 } };
static const uint32_t birthdays_indices[] = { WYKE, HAJO, TROUWDAG };
