/**
 * Autogenerated header file for the wordclock
 *   23 words encoded
 *   14/103 empty squares
 *
 * K W A R T I E N F U 
 * S V I J F F O V E R 
 * W V O O R J H A L F 
 * A O Z E S A U N I T 
 * G C R E V N T E C W 
 * A V H N V J I G I A 
 * P I I T W E E E A A 
 * U J I E Q L N N L L 
 * C F M A R L O E S F 
 * K X D R I E N U U R 
 */

static const uint32_t VIJF       = (1ul << 0);
static const uint32_t TIEN       = (1ul << 1);
static const uint32_t KWART      = (1ul << 2);
static const uint32_t VOOR       = (1ul << 3);
static const uint32_t OVER       = (1ul << 4);
static const uint32_t HALF       = (1ul << 5);
static const uint32_t TWAALF     = (1ul << 6);
static const uint32_t EEN        = (1ul << 7);
static const uint32_t TWEE       = (1ul << 8);
static const uint32_t DRIE       = (1ul << 9);
static const uint32_t VIER       = (1ul << 10);
static const uint32_t VIJF_      = (1ul << 11);
static const uint32_t ZES        = (1ul << 12);
static const uint32_t ZEVEN      = (1ul << 13);
static const uint32_t ACHT       = (1ul << 14);
static const uint32_t NEGEN      = (1ul << 15);
static const uint32_t TIEN_      = (1ul << 16);
static const uint32_t ELF        = (1ul << 17);
static const uint32_t UUR        = (1ul << 18);
static const uint32_t JANJELLE   = (1ul << 19);
static const uint32_t MARLOES    = (1ul << 20);
static const uint32_t PUCK       = (1ul << 21);
static const uint32_t FELICIA    = (1ul << 22);
static const uint32_t HORIZONTAL = (1ul << 23);
static const uint32_t VERTICAL   = (1ul << 24);
static const uint32_t DIAGONAL   = (1ul << 25);

static const uint32_t hours[] = { TWAALF, EEN,   TWEE, DRIE,  VIER,  VIJF_,
                                  ZES,    ZEVEN, ACHT, NEGEN, TIEN_, ELF };

static const uint32_t matrix[] = {
  KWART | HORIZONTAL,
  KWART | HORIZONTAL,
  KWART | HORIZONTAL,
  KWART | HORIZONTAL,
  TIEN | HORIZONTAL | KWART | HORIZONTAL,
  TIEN | HORIZONTAL,
  TIEN | HORIZONTAL,
  TIEN | HORIZONTAL,
  FELICIA | VERTICAL,
  0ul,
  0ul,
  VIJF | HORIZONTAL,
  VIJF | HORIZONTAL,
  VIJF | HORIZONTAL,
  VIJF | HORIZONTAL,
  0ul,
  OVER | HORIZONTAL,
  OVER | HORIZONTAL,
  OVER | HORIZONTAL | FELICIA | VERTICAL,
  OVER | HORIZONTAL,
  0ul,
  VOOR | HORIZONTAL,
  VOOR | HORIZONTAL,
  VOOR | HORIZONTAL,
  VOOR | HORIZONTAL,
  JANJELLE | VERTICAL,
  HALF | HORIZONTAL,
  HALF | HORIZONTAL,
  HALF | HORIZONTAL | FELICIA | VERTICAL,
  HALF | HORIZONTAL,
  ACHT | DIAGONAL,
  0ul,
  ZES | HORIZONTAL | ZEVEN | DIAGONAL,
  EEN | VERTICAL | ZES | HORIZONTAL,
  ZES | HORIZONTAL,
  JANJELLE | VERTICAL,
  0ul,
  NEGEN | VERTICAL,
  FELICIA | VERTICAL,
  TWAALF | VERTICAL,
  0ul,
  ACHT | DIAGONAL,
  0ul,
  EEN | VERTICAL | ZEVEN | DIAGONAL,
  0ul,
  JANJELLE | VERTICAL,
  TIEN | VERTICAL,
  NEGEN | VERTICAL,
  FELICIA | VERTICAL,
  TWAALF | VERTICAL,
  0ul,
  VIER | DIAGONAL | VIJF | VERTICAL,
  ACHT | DIAGONAL,
  EEN | VERTICAL,
  ZEVEN | DIAGONAL,
  JANJELLE | VERTICAL,
  TIEN | VERTICAL,
  NEGEN | VERTICAL,
  FELICIA | VERTICAL,
  TWAALF | VERTICAL,
  PUCK | VERTICAL,
  VIJF | VERTICAL,
  VIER | DIAGONAL,
  TWEE | HORIZONTAL | ACHT | DIAGONAL,
  TWEE | HORIZONTAL,
  TWEE | HORIZONTAL | ZEVEN | DIAGONAL | JANJELLE | VERTICAL,
  TWEE | HORIZONTAL | TIEN | VERTICAL,
  NEGEN | VERTICAL | ELF | DIAGONAL,
  FELICIA | VERTICAL,
  TWAALF | VERTICAL,
  PUCK | VERTICAL,
  VIJF | VERTICAL,
  0ul,
  VIER | DIAGONAL,
  0ul,
  JANJELLE | VERTICAL,
  ZEVEN | DIAGONAL | TIEN | VERTICAL,
  NEGEN | VERTICAL,
  ELF | DIAGONAL,
  TWAALF | VERTICAL,
  PUCK | VERTICAL,
  VIJF | VERTICAL,
  MARLOES | HORIZONTAL,
  MARLOES | HORIZONTAL,
  VIER | DIAGONAL | MARLOES | HORIZONTAL,
  JANJELLE | VERTICAL | MARLOES | HORIZONTAL,
  MARLOES | HORIZONTAL,
  MARLOES | HORIZONTAL,
  MARLOES | HORIZONTAL,
  TWAALF | VERTICAL | ELF | DIAGONAL,
  PUCK | VERTICAL,
  0ul,
  DRIE | HORIZONTAL,
  DRIE | HORIZONTAL,
  DRIE | HORIZONTAL,
  DRIE | HORIZONTAL | JANJELLE | VERTICAL,
  0ul,
  UUR | HORIZONTAL,
  UUR | HORIZONTAL,
  UUR | HORIZONTAL
};

